@startuml weather uml
title Weather Feature

' presentation

class WeatherViewModel {
    - getLocationUseCase: GetLocationUseCase
    - getWeatherGeoUseCase: GetWeatherGeoUseCase
    - requestWeatherUseCase: RequestWeatherUseCase
    - queryNowWeatherUseCase: QueryNowWeatherUseCase
    - queryDailyWeatherUseCase: QueryDailyWeatherUseCase
    - queryHourlyWeatherUseCase: QueryHourlyWeatherUseCase
    - getWeatherGeoListUseCase: GetWeatherGeoListUseCase
    - getNowWeatherUseCase: GetNowWeatherUseCase
    - getDailyWeatherUseCase: GetDailyWeatherUseCase
    - getHourlyWeatherUseCase: GetHourlyWeatherUseCase
    - saveWeatherUseCase: SaveWeatherUseCase
    - queryAllWeatherUseCase: QueryAllWeatherUseCase
    + observeLocationChange(): Void
    - getWeatherGeo(lat: Double, lon: Double): WeatherGeo
    - requestWeather(id: String, isCurrentLocation: Boolean): Void
}

WeatherViewModel ..> GetLocationUseCase
WeatherViewModel ..> GetWeatherGeoUseCase
WeatherViewModel ..> RequestWeatherUseCase
WeatherViewModel ..> QueryNowWeatherUseCase
WeatherViewModel ..> QueryDailyWeatherUseCase
WeatherViewModel ..> QueryHourlyWeatherUseCase
WeatherViewModel ..> GetWeatherGeoListUseCase
WeatherViewModel ..> GetNowWeatherUseCase
WeatherViewModel ..> GetDailyWeatherUseCase
WeatherViewModel ..> GetHourlyWeatherUseCase
WeatherViewModel ..> SaveWeatherUseCase
WeatherViewModel ..> QueryAllWeatherUseCase


' domain

interface ILocationRepository {
    + getLocation(): Flow<Location>
}

interface IWeatherRepository {
    + getWeatherGeo(lat: Double, lon: Double): WeatherGeo
    + requestWeather(id: String, isCurrentLocation: Boolean): Void
    + queryNowWeather(id: String): Flow<NowWeather>
    + queryDailyWeather(id: String): Flow<List<DailyWeather>>
    + queryHourlyWeather(id: String): Flow<List<HourlyWeather>>
    + getGeoList(keyword: String): List<WeatherGeo>
    + getNowWeather(locationId: String): NowWeather
    + getDailyWeather(locationId: String): List<DailyWeather>
    + getHourlyWeather(locationId: String): List<HourlyWeather>
    + saveWeather(weather: Weather): Void
    + queryAllWeather(): Flow<List<Weather>>
}

class GetLocationUseCase {
    - repository: ILocationRepository
    + invoke(): Flow<Location>
}

class GetWeatherGeoUseCase {
    - repository: IWeatherRepository
    + invoke(lat: Double, lon: Double): WeatherGeo
}

class RequestWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String, isCurrentLocation: Boolean): Void
}

class QueryNowWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): Flow<NowWeather>
}

class QueryDailyWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): Flow<List<DailyWeather>>
}

class QueryHourlyWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): Flow<List<HourlyWeather>>
}

class GetWeatherGeoListUseCase {
    - repository: IWeatherRepository
    + invoke(keyword: String): List<WeatherGeo>
}

class GetNowWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): NowWeather
}

class GetDailyWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): List<DailyWeather>
}

class GetHourlyWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(id: String): List<HourlyWeather>
}

class SaveWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(weather: Weather): Void
}

class QueryAllWeatherUseCase {
    - repository: IWeatherRepository
    + invoke(): Flow<List<Weather>>
}

GetWeatherGeoUseCase ..> IWeatherRepository
RequestWeatherUseCase ..> IWeatherRepository
GetLocationUseCase ..> ILocationRepository
QueryNowWeatherUseCase ..> IWeatherRepository
QueryDailyWeatherUseCase ..> IWeatherRepository
QueryHourlyWeatherUseCase ..> IWeatherRepository
GetWeatherGeoListUseCase ..> IWeatherRepository
GetNowWeatherUseCase ..> IWeatherRepository
GetDailyWeatherUseCase ..> IWeatherRepository
GetHourlyWeatherUseCase ..> IWeatherRepository
SaveWeatherUseCase ..> IWeatherRepository
QueryAllWeatherUseCase ..> IWeatherRepository
ILocationRepository <|.. LocationRepositroy
IWeatherRepository <|.. WeatherRepository


' data

class LocationRepositroy {
    - locationManager: LocationManager
    - appContext: Context
    + getLocation(): Flow<Location>
}

class WeatherRepository {
    - weatherRemoteDataSource: WeatherRemoteDataSource
    - weatherLocalDataSource: WeatherLocalDataSource
    + getWeatherGeo(lat: Double, lon: Double): WeatherGeo
    + requestWeather(id: String, isCurrentLocation: Boolean): Void
    + queryNowWeather(id: String): Flow<NowWeather>
    + queryDailyWeather(id: String): Flow<List<DailyWeather>>
    + queryHourlyWeather(id: String): Flow<List<HourlyWeather>>
    + getGeoList(keyword: String): List<WeatherGeo>
    + getNowWeather(locationId: String): NowWeather
    + getDailyWeather(locationId: String): List<DailyWeather>
    + getHourlyWeather(locationId: String): List<HourlyWeather>
    + saveWeather(weather: Weather): Void
    + queryAllWeather(): Flow<List<Weather>>
}

class WeatherRemoteDataSource {
    - qweatherApi: QWeatherApi
    + getGeo(lat: Double, lon: Double): QWeatherGeoDTO
    + getNowWeather(locationId: String): QWeatherNowDTO
    + getDailyWeather(locationId: String): QWeatherDailyDTO
    + getHourlyWeather(locationId: String): QWeatherHourlyDTO
    + getGeoList(keyword: String): QWeatherGeoDTO
}

class WeatherLocalDataSource {
    - weatherDao: WeatherDao
    + insertWeatherGeo(geo: QWeatherGeoEntity, isCurrentLocation: Boolean): Long
    + insertNowWeather(now: QWeatherNowEntity, isCurrentLocation: Boolean): Long
    + insertDailyWeather(daily: List<QWeatherDailyEntity>, isCurrentLocation: Boolean): List<Long>
    + insertHourlyWeather(hourly: List<QWeatherHourlyEntity>, isCurrentLocation: Boolean): List<Long>
    + queryNowWeather(locationId: String): Flow<QWeatherNowEntity>
    + queryDailyWeather(locationId: String): Flow<List<QWeatherDailyEntity>>
    + queryHourlyWeather(locationId: String): Flow<List<QWeatherHourlyEntity>>
    + queryAllWeather(): Flow<List<QWeatherEntity>>
}

interface QWeatherApi {
    + getGeo(location: String): QWeatherGeoDTO
    + getNowWeather(location: String): QWeatherNowDTO
    + getDailyWeather(location: String): QWeatherDailyDTO
    + getHourlyWeather(location: String): QWeatherHourlyDTO
}

interface WeatherDao {
    + deleteOldLocationQWeatherGeo(): Long
    + insertQWeatherGeo(geo: QWeatherGeoEntity): Long
    + deleteOldLocationQWeatherNow(): Long
    + insertQWeatherNow(now: QWeatherNowEntity): Long
    + deleteOldLocationQWeatherDaily(): List<Long>
    + insertQWeatherDaily(daily: List<QWeatherDailyEntity>): List<Long>
    + deleteOldLocationQWeatherHourly(): List<Long>
    + insertQWeatherHourly(hourly: List<QWeatherHourlyEntity>): List<Long>
    + queryQWeatherNow(locationId: String): Flow<QWeatherNowEntity>
    + queryQWeatherDaily(locationId: String): Flow<List<QWeatherDailyEntity>>
    + queryQWeatherHourly(locationId: String): Flow<List<QWeatherHourlyEntity>>
    + queryQWeatherList(): Flow<List<QWeatherEntity>>
}

WeatherRepository ..> WeatherRemoteDataSource
WeatherRepository ..> WeatherLocalDataSource
WeatherRemoteDataSource ..> QWeatherApi
WeatherLocalDataSource ..> WeatherDao

@enduml